name: Sync to public
on:
  push:
    tags:
      - '*'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current tag
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
          repository: datgizmo/gh-sync-target
          force: true
          tags: true
