name: Sync to public
on:
  push:
    tags:
      - '*'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: |
          git remote add fork git@github.com:DatGizmo/gh-sync-target.git
          git push fork ${{ github.ref_name }}
